wip: Add ledger plugin functionality
obsidiansystems/ckb-plugin-ledger pull request #1
Opened 2020-07-21 12:53 UTC by dfordivam

2020-07-27 22:03 UTC, jhartzell42 requested changes

2020-07-27 22:03 UTC, jhartzell42 commented on src/keystore.rs
> +// impl AbstractPrivKey for LedgerCap {
We don't want a huge commented-out section in an MR. Why is this commented out instead of just removed?

2020-07-27 22:03 UTC, jhartzell42 commented
Besides the comments, which I am confused by, looks good.

2020-07-28 04:27 UTC, dfordivam commented on src/keystore.rs
> +// impl AbstractPrivKey for LedgerCap {
I can get rid of this if required.
I put this code back in the next MR though.

2020-07-28 06:29 UTC, dfordivam commented on src/keystore.rs
> +// impl AbstractPrivKey for LedgerCap {
Fixed

2020-07-28 13:47 UTC, merged